package br.ufes.informatica.musicplus.core.persistence;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.musicplus.core.domain.Artista;
import br.ufes.informatica.musicplus.core.domain.Colecao;
import br.ufes.informatica.musicplus.core.domain.TipoGenero;
import br.ufes.informatica.musicplus.core.domain.TipoPais;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface ArtistaDAO extends BaseDAO<Artista> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public List buscarPorNome(String nome);

	/** TODO: generated by FrameWeb. Should be documented. */
	public List buscarPorGenero(TipoGenero genero);

	/** TODO: generated by FrameWeb. Should be documented. */
	public List buscarPorPais(TipoPais pais);

	/** TODO: generated by FrameWeb. Should be documented. */
	public List buscarPorColecao(Colecao colecao);

}