package br.ufes.informatica.musicplus.core.persistence;

import java.util.List;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.inf.nemo.jbutler.ejb.persistence.exceptions.MultiplePersistentObjectsFoundException;
import br.ufes.inf.nemo.jbutler.ejb.persistence.exceptions.PersistentObjectNotFoundException;
import br.ufes.informatica.musicplus.core.domain.Artista;
import br.ufes.informatica.musicplus.core.domain.TipoGenero;
import br.ufes.informatica.musicplus.core.domain.TipoPais;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface ArtistaDAO extends BaseDAO<Artista> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Artista> buscarPorNome(String nome);

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Artista> buscarPorGenero(TipoGenero genero) throws PersistentObjectNotFoundException, MultiplePersistentObjectsFoundException;

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Artista> buscarPorPais(TipoPais pais) throws PersistentObjectNotFoundException, MultiplePersistentObjectsFoundException;

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Artista> buscarGeral(String nomeDoArtista, TipoGenero genero, TipoPais pais, Boolean ranking, Integer numero);

}