package br.ufes.informatica.musicplus.core.persistence;

import java.util.List;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.musicplus.core.domain.Artista;
import br.ufes.informatica.musicplus.core.domain.Album;
import br.ufes.informatica.musicplus.core.domain.Musica;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface ColecaoDAO extends BaseDAO<Album> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Album> buscarPorArtista(Artista artista);

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Album> buscarPorMusica(Musica musica);

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Album> buscarPorNome(String nome);

}