package br.ufes.informatica.musicplus.core.persistence;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;
import br.ufes.informatica.musicplus.core.domain.Musica;
import br.ufes.informatica.musicplus.core.domain.Playlist;
import br.ufes.informatica.musicplus.core.domain.Usuario;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class PlaylistDAOJPA extends BaseJPADAO<Playlist> implements PlaylistDAO {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@PersistenceContext
	private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void adicionarMusica(Musica musica, Playlist playlist) {
		// FIXME: auto-generated method stub
		return;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void removerMusica(Musica musica, Playlist playlist) {
		// FIXME: auto-generated method stub
		return;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Playlist buscarPorNome(String nome, Usuario usuario) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List listarMusicasDaPlaylist(Playlist playlist) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List buscarPorUsuario(Usuario usuario) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List listarPlaylistsDoUsuario(Usuario usuario) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Boolean checarSeMusicaEstaNaPlaylist(Musica musica, Playlist playlist) {
		// FIXME: auto-generated method stub
		return null;
	}

}