package br.ufes.informatica.musicplus.core.persistence;

import java.util.List;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.musicplus.core.domain.Playlist;
import br.ufes.informatica.musicplus.core.domain.Usuario;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface PlaylistDAO extends BaseDAO<Playlist> {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Playlist> buscarPorUsuario(Usuario usuario);

}