package br.ufes.informatica.musicplus.core.persistence;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.musicplus.core.domain.Playlist;
import br.ufes.informatica.musicplus.core.domain.Usuario;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface PlaylistDAO extends BaseDAO<Playlist> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public Playlist buscarPorNome(String nome, Usuario usuario);

	/** TODO: generated by FrameWeb. Should be documented. */
	public List buscarPorUsuario(Usuario usuario);

}