package br.ufes.informatica.musicplus.core.persistence;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import br.ufes.informatica.musicplus.core.domain.Artista;
import br.ufes.informatica.musicplus.core.domain.TipoGenero;
import br.ufes.informatica.musicplus.core.domain.Usuario;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class UsuarioDAOJPA extends PessoaDAOJPA implements UsuarioDAO {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@PersistenceContext
	private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void favoritarArtista(Artista artista, Usuario usuario) {
		// FIXME: auto-generated method stub
		return;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void favoritarGenero(TipoGenero genero, Usuario usuario) {
		// FIXME: auto-generated method stub
		return;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List listarArtistasFavoritos(Usuario usuario) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List listarGenerosFavoritos(Usuario usuario) {
		// FIXME: auto-generated method stub
		return null;
	}

}