package br.ufes.informatica.musicplus.core.persistence;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.musicplus.core.domain.Usuario;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface UsuarioDAO extends BaseDAO<Usuario> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public Usuario buscarPorEmail(String email);

}