package br.ufes.informatica.musicplus.core.application;

import java.io.Serializable;

import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface MusicaService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public List buscarMusica(String NomeDaMusica, String NomeDoArtista);

}