package br.ufes.informatica.musicplus.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class SugestaoServiceBean implements SugestaoService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private MusicaDAO musicaDAO;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private ArtistaDAO artistaDAO;
	
	
	

	
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List pedirSugestaoArtista(String rankingOuAleatorio, TipoPais pais, Integer numero, TipoGenero genero) {
		// FIXME: auto-generated method stub
		return null;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List pedirSugestaoMusica(String RankingOuAleatorio, TipoIdioma idioma, Integer numero, TipoGenero genero) {
		// FIXME: auto-generated method stub
		return null;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	private List selecionarArtistasAleatorios(List listaArtistas, Integer numero) {
		// FIXME: auto-generated method stub
		return null;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	private List selecionarMusicasAleatorias(List listaMusicas, Integer numero) {
		// FIXME: auto-generated method stub
		return null;
	}
	
}