package br.ufes.informatica.musicplus.core.domain;

import javax.persistence.Entity;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Admin extends PersistentObjectSupport implements Comparable<Admin> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Admin o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}