package br.ufes.informatica.musicplus.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Colecao extends PersistentObjectSupport implements Comparable<Colecao> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private List tipoColecao;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@NotNull  @Temporal(TemporalType.DATE)
	private Date dataLancamento;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToMany(mappedBy="Target")
		private Set<Artista> Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToMany(mappedBy="Target")
		private Set<Musica> Source;
		
	




	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for tipoColecao. */
	public List getTipoColecao() {
		return tipoColecao;
	}
	
	/** Setter for tipoColecao. */
	public void setTipoColecao(List tipoColecao) {
		this.tipoColecao = tipoColecao;
	}

	/** Getter for dataLancamento. */
	public Date getDataLancamento() {
		return dataLancamento;
	}
	
	/** Setter for dataLancamento. */
	public void setDataLancamento(Date dataLancamento) {
		this.dataLancamento = dataLancamento;
	}




		
		/** Getter for Source. */
		public Set<Artista> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<Artista> Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Source. */
		public Set<Musica> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<Musica> Source) {
			this.Source = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Colecao o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}