package br.ufes.informatica.musicplus.core.controller;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.musicplus.core.application.ArtistaService;
import br.ufes.informatica.musicplus.core.application.MusicaService;
import br.ufes.informatica.musicplus.core.domain.Artista;
import br.ufes.informatica.musicplus.core.domain.Musica;
import br.ufes.informatica.musicplus.core.domain.TipoGenero;
import br.ufes.informatica.musicplus.core.domain.TipoIdioma;

@Model
@SessionScoped
public class CadastroMusicaController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private ArtistaService artistaService;
	
	@EJB
	private MusicaService musicaService;

	private String nome ;
		
	private Date duracao;

	private Date dataDeLancamento ;

	private TipoIdioma[] todosOsIdiomas;

	private TipoIdioma idiomaEscolhido;	
	
	private TipoGenero[] generosEscolhidos;

	private TipoGenero[] todosOsGeneros ;
	
	private int numVezesFavoritado;
	
	private Musica musica ;

	private Artista artistaEscolhido ;

	private List<Artista> artistas ;

	private List<Musica> musicas ;
	
	private Boolean desabilitarBotaoAdRmArtista ;
	
	@PostConstruct
	public void init() {
		todosOsGeneros = TipoGenero.todos();
		todosOsIdiomas = TipoIdioma.todos();
		numVezesFavoritado = 0;
		desabilitarBotaoAdRmArtista = true ;
	}

	public Boolean getDesabilitarBotaoAdRmArtista() {
		return desabilitarBotaoAdRmArtista;
	}

	public void setDesabilitarBotaoAdRmArtista(Boolean desabilitarBotaoAdRmArtista) {
		this.desabilitarBotaoAdRmArtista = desabilitarBotaoAdRmArtista;
	}
	
	public void habilitarBotaoAdRmArtista() {
		desabilitarBotaoAdRmArtista = false ;
	}

	public void setDuracao(Date duracao) {
		this.duracao = duracao;
	}

	public void setDataDeLancamento(Date dataDeLancamento) {
		this.dataDeLancamento = dataDeLancamento;
	}

	public void setIdiomaEscolhido(TipoIdioma idiomaEscolhido) {
		this.idiomaEscolhido = idiomaEscolhido;
	}

	public void setGenerosEscolhidos(TipoGenero[] generosEscolhidos) {
		this.generosEscolhidos = generosEscolhidos;
	}

	public void setNumVezesFavoritado(int numVezesFavoritado) {
		this.numVezesFavoritado = numVezesFavoritado;
	}
	
	public Date getDuracao() {
		return duracao;
	}
	
	public Date getDataDeLancamento() {
		return dataDeLancamento;
	}

	public TipoIdioma getIdiomaEscolhido() {
		return idiomaEscolhido;
	}
	
    public TipoGenero[] getTodosOsGeneros() {
        return todosOsGeneros;
    }
    
    public TipoIdioma[] getTodosOsIdiomas() {
        return todosOsIdiomas;
    }
    
    public int getNumVezesFavoritado() {
		return numVezesFavoritado;
	}

	public TipoGenero[] getGenerosEscolhidos() {
        return generosEscolhidos;
    }
    
    public String salvarMusica() {
    	Musica musica = new Musica();
    	for (TipoGenero g : generosEscolhidos) {
    		musica.addGenero(g);
    	}
    	musica.setIdioma(idiomaEscolhido);
    	musica.setNome(nome);
    	musica.setNumVezesFavoritado(numVezesFavoritado);
    	musica.setDataLancamento(dataDeLancamento);
    	musica.setDuracao(duracao);
    	musicaService.save(musica);
    	this.musica = musica ;
    	this.nome = null;
    	return musicaArtistaAdicionar() ;
    }
    
	public Musica getMusica() {
		return musica;
	}

	public void setMusica(Musica musica) {
		this.musica = musica;
	}
	
	public String descobrirArtistas(){
		artistas = artistaService.buscarPorNome(nome);
		List<Artista> artistasRemovidos = new ArrayList<Artista>();
		for (Artista a : artistas) {
			if (musica.getArtistas().contains(a)) {
				artistasRemovidos.add(a) ;
			}
		}
		artistas.removeAll(artistasRemovidos) ;
		nome = null ;
		return musicaArtistaAdicionar() ;
	}
	
	public String redirectToMusicaArtista() {
		return musicaArtistaAdicionar() ;
	}
	
	public String redirectToMusicaArtistaRemover() {
		return musicaArtistaRemover() ;
	}
	
	public void auxMusicaArtistaDefaults() {
		musicas = null ;
		artistaEscolhido = null ;
		desabilitarBotaoAdRmArtista = true ;
	}
	
	public String musicaArtistaRemover() {
		auxMusicaArtistaDefaults() ;
		return "/core/cadastrar/MusicaArtistaRemover.xhtml?faces-redirect=true" ;
	}
	
	public String musicaArtistaAdicionar() {
		auxMusicaArtistaDefaults() ;
		return "/core/cadastrar/MusicaArtistaAdicionar.xhtml?faces-redirect=true" ;
	}
	public String descobrirMusicas(){
		musica = null ;
		artistas = null ;
		musicas = musicaService.buscarPorNome(nome);
		nome = null ;
		desabilitarBotaoAdRmArtista = true ;
		return "/core/cadastrar/BuscarMusica.xhtml?faces-redirect=true" ;
	}
	
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Artista getArtistaEscolhido() {
		return artistaEscolhido;
	}

	public void setArtistaEscolhido(Artista artistaEscolhido) {
		this.artistaEscolhido = artistaEscolhido;
	}

	public List<Artista> getArtistas() {
		return artistas;
	}

	public List<Musica> getMusicas() {
		return musicas;
	}

	public void salvarRemoverAux() {
		musicaService.save(musica);
		artistas = null ;
		musicas = null ;
		musica = null ;
		desabilitarBotaoAdRmArtista = true ;
	}
	public String salvarArtistaMusica() {
		this.musica.addArtista(this.artistaEscolhido) ;
		salvarRemoverAux() ;
		return "/index.xhtml?faces-redirect=true" ;
	}
	
	public String removerArtistaMusica() {
		this.musica.removerArtista(this.artistaEscolhido) ;
		salvarRemoverAux() ;
		return "/index.xhtml?faces-redirect=true" ;
	}
}
