package br.ufes.informatica.musicplus.core.controller;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.musicplus.core.application.SugestaoService;
import br.ufes.informatica.musicplus.core.domain.TipoGenero;
import br.ufes.informatica.musicplus.core.domain.TipoIdioma;
import br.ufes.informatica.musicplus.core.domain.Musica;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
@SessionScoped
public class SugestaoMusicaController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private SugestaoService sugestaoService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List<Musica> listaDeMusicas;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Integer numSugestoes;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String porRankingOuAleatorio;

	private TipoIdioma[] idiomasEscolhidos;
	
	private TipoIdioma[] todosOsIdiomas;
	
	private TipoGenero[] generosEscolhidos;

	private TipoGenero[] todosOsGeneros ;
	
	private boolean allGeneros ;
	
	private boolean allIdiomas ;

	private boolean warningVazioGenero ;
	
	private boolean warningVazioIdioma ;
	
	@PostConstruct
	public void init() {
		auxClean() ;
	}
	
	public void auxClean() {
		todosOsGeneros = TipoGenero.todos();
		todosOsIdiomas = TipoIdioma.todos();
		allGeneros = true ;
		allIdiomas = true; 
		idiomasEscolhidos = todosOsIdiomas ;
		generosEscolhidos = todosOsGeneros ;
		numSugestoes = null; 
		warningVazioGenero = false ;
		warningVazioIdioma = false ;
	}

	/** Getter for listaDeMusicas. */
	public List<Musica> getListaDeMusicas() {
		return listaDeMusicas;
	}

	/** Setter for listaDeMusicas. */
	public void setListaDeMusicas(List<Musica> listaDeMusicas) {
		this.listaDeMusicas = listaDeMusicas;
	}

	/** Getter for numSugestoes. */
	public Integer getNumSugestoes() {
		return numSugestoes;
	}

	/** Setter for numSugestoes. */
	public void setNumSugestoes(Integer numSugestoes) {
		this.numSugestoes = numSugestoes;
	}

	/** Getter for porRankingOuAleatorio. */
	public String getPorRankingOuAleatorio() {
		return porRankingOuAleatorio;
	}

	/** Setter for porRankingOuAleatorio. */
	public void setPorRankingOuAleatorio(String porRankingOuAleatorio) {
		this.porRankingOuAleatorio = porRankingOuAleatorio;
	}

	public TipoIdioma[] getIdiomasEscolhidos() {
		return idiomasEscolhidos;
	}

	public void setIdiomasEscolhidos(TipoIdioma[] idiomasEscolhidos) {
		this.idiomasEscolhidos = idiomasEscolhidos;
	}

	public TipoIdioma[] getTodosOsIdiomas() {
		return todosOsIdiomas;
	}

	public TipoGenero[] getGenerosEscolhidos() {
		return generosEscolhidos;
	}

	public void setGenerosEscolhidos(TipoGenero[] generosEscolhidos) {
		this.generosEscolhidos = generosEscolhidos;
	}

	public TipoGenero[] getTodosOsGeneros() {
		return todosOsGeneros;
	}
	
	public void escolherTodosOsGeneros() {
		if (allGeneros == true) {
			generosEscolhidos = todosOsGeneros ;
			warningVazioGenero = false ;
		}else {
			generosEscolhidos = null ;
			warningVazioGenero = true ;
		}
	}
	
	public void dispensarTodosOsGeneros() {
		warningVazioGenero = true ;
		allGeneros = false ;
		if (generosEscolhidos == null) {
			return ;
		}
		if (generosEscolhidos.length == 0) {
			return ;
		}
		warningVazioGenero = false ;
		allGeneros = true ;
		if (generosEscolhidos.length != todosOsGeneros.length) {
			allGeneros = false ;
		}
		return ;
	}
	
	public void escolherTodosOsIdiomas() {
		if (allIdiomas == true) {
			idiomasEscolhidos = todosOsIdiomas ;
			warningVazioIdioma = false ;
		}else {
			idiomasEscolhidos = null ;
			warningVazioIdioma = true ;
		}
	}
	
	public void dispensarTodosOsIdiomas() {
		warningVazioIdioma = true ;
		allIdiomas = false ;
		if (idiomasEscolhidos == null) {
			return ;
		}
		if (idiomasEscolhidos.length == 0) {
			return ;
		}
		warningVazioIdioma = false ;
		allIdiomas = true ;
		if (idiomasEscolhidos.length != todosOsIdiomas.length) {
			allIdiomas = false ;
		}
		return ;
	}

	public boolean isAllGeneros() {
		return allGeneros;
	}

	public void setAllGeneros(boolean allGeneros) {
		this.allGeneros = allGeneros;
	}

	public boolean isAllIdiomas() {
		return allIdiomas;
	}

	public void setAllIdiomas(boolean allIdiomas) {
		this.allIdiomas = allIdiomas;
	}

	public boolean isWarningVazioGenero() {
		return warningVazioGenero;
	}

	public void setWarningVazioGenero(boolean warningVazioGenero) {
		this.warningVazioGenero = warningVazioGenero;
	}

	public boolean isWarningVazioIdioma() {
		return warningVazioIdioma;
	}

	public void setWarningVazioIdioma(boolean warningVazioIdioma) {
		this.warningVazioIdioma = warningVazioIdioma;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String pedirSugestaoMusica() {
		if (warningVazioGenero || warningVazioIdioma) {
			listaDeMusicas = null ;
		}else {
			List<TipoIdioma> idiomas = new ArrayList<TipoIdioma>(); 
			for (TipoIdioma p : idiomasEscolhidos) {
				idiomas.add(p);
			}
			List<TipoGenero> generos = new ArrayList<TipoGenero>(); 
			for (TipoGenero g : generosEscolhidos) {
				generos.add(g);
			}
			listaDeMusicas = sugestaoService.pedirSugestaoMusica(porRankingOuAleatorio, idiomas, numSugestoes, null);
		}
		auxClean();
		return "/core/sugestao/MusicasEncontrados.xhtml?faces-redirect=true" ;
	}

}