package br.ufes.informatica.musicplus.core.controller;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.musicplus.core.application.SugestaoService;
import br.ufes.informatica.musicplus.core.domain.TipoGenero;
import br.ufes.informatica.musicplus.core.domain.TipoIdioma;
import br.ufes.informatica.musicplus.core.domain.TipoPais;
import br.ufes.informatica.musicplus.core.domain.Musica;
import br.ufes.informatica.musicplus.core.domain.Artista;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class SugestaoMusicaController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private SugestaoService sugestaoService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List<Musica> listaDeMusicas;

	/** TODO: generated by FrameWeb. Should be documented. */
	private int numSugestoes;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String porRankingOuAleatorio;

	/** TODO: generated by FrameWeb. Should be documented. */
	
	private TipoGenero[] generosEscolhidos;

	private TipoGenero[] todosOsGeneros ;
	
	private TipoIdioma[] todosOsIdiomas;

	private TipoIdioma[] idiomasEscolhidos;

	@PostConstruct
	public void init() {
		todosOsGeneros = TipoGenero.todos();
		todosOsIdiomas = TipoIdioma.todos();
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String pedirSugestaoArtista() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String pedirSugestaoMusica() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** Getter for listaDeMusicas. */
	public List<Musica> getListaDeMusicas() {
		return listaDeMusicas;
	}

	/** Setter for listaDeMusicas. */
	public void setListaDeMusicas(List<Musica> listaDeMusicas) {
		this.listaDeMusicas = listaDeMusicas;
	}

	/** Getter for numSugestoes. */
	public int getNumSugestoes() {
		return numSugestoes;
	}

	/** Setter for numSugestoes. */
	public void setNumSugestoes(int numSugestoes) {
		this.numSugestoes = numSugestoes;
	}

	/** Getter for porRankingOuAleatorio. */
	public String getPorRankingOuAleatorio() {
		return porRankingOuAleatorio;
	}

	/** Setter for porRankingOuAleatorio. */
	public void setPorRankingOuAleatorio(String porRankingOuAleatorio) {
		this.porRankingOuAleatorio = porRankingOuAleatorio;
	}

	public TipoGenero[] getGenerosEscolhidos() {
		return generosEscolhidos;
	}

	public void setGenerosEscolhidos(TipoGenero[] generosEscolhidos) {
		this.generosEscolhidos = generosEscolhidos;
	}

	public TipoGenero[] getTodosOsGeneros() {
		return todosOsGeneros;
	}

	public TipoIdioma[] getTodosOsIdiomas() {
		return todosOsIdiomas;
	}

	public void setIdiomasEscolhidos(TipoIdioma[] idiomasEscolhidos) {
		this.idiomasEscolhidos = idiomasEscolhidos;
	}
	
	public TipoIdioma[] getIdiomasEscolhidos() {
		return idiomasEscolhidos;
	}

}