package br.ufes.informatica.musicplus.core.controller;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.musicplus.core.application.SugestaoService;
import br.ufes.informatica.musicplus.core.domain.TipoGenero;
import br.ufes.informatica.musicplus.core.domain.TipoIdioma;
import br.ufes.informatica.musicplus.core.domain.TipoPais;
import br.ufes.informatica.musicplus.core.domain.Musica;
import br.ufes.informatica.musicplus.core.domain.Artista;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class SugestaoArtistaController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private SugestaoService sugestaoService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List<Artista> listaDeArtistas;

	/** TODO: generated by FrameWeb. Should be documented. */
	private int numSugestoes;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String porRankingOuAleatorio;

	private TipoPais[] paisesEscolhidos;
	
	private TipoPais[] todosOsPaises;
	
	private TipoGenero[] generosEscolhidos;

	private TipoGenero[] todosOsGeneros ;
	
	private boolean allGeneros ;
	
	private boolean allPaises ;

	
	@PostConstruct
	public void init() {
		todosOsGeneros = TipoGenero.todos();
		todosOsPaises = TipoPais.todos();
		allGeneros = false ;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String pedirSugestaoArtista() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String pedirSugestaoMusica() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** Getter for listaDeArtistas. */
	public List<Artista> getListaDeArtistas() {
		return listaDeArtistas;
	}

	/** Setter for listaDeArtistas. */
	public void setListaDeArtistas(List<Artista> listaDeArtistas) {
		this.listaDeArtistas = listaDeArtistas;
	}

	/** Getter for numSugestoes. */
	public int getNumSugestoes() {
		return numSugestoes;
	}

	/** Setter for numSugestoes. */
	public void setNumSugestoes(int numSugestoes) {
		this.numSugestoes = numSugestoes;
	}

	/** Getter for porRankingOuAleatorio. */
	public String getPorRankingOuAleatorio() {
		return porRankingOuAleatorio;
	}

	/** Setter for porRankingOuAleatorio. */
	public void setPorRankingOuAleatorio(String porRankingOuAleatorio) {
		this.porRankingOuAleatorio = porRankingOuAleatorio;
	}

	public TipoPais[] getPaisesEscolhidos() {
		return paisesEscolhidos;
	}

	public void setPaisesEscolhidos(TipoPais[] paisesEscolhidos) {
		this.paisesEscolhidos = paisesEscolhidos;
	}

	public TipoPais[] getTodosOsPaises() {
		return todosOsPaises;
	}

	public TipoGenero[] getGenerosEscolhidos() {
		return generosEscolhidos;
	}

	public void setGenerosEscolhidos(TipoGenero[] generosEscolhidos) {
		this.generosEscolhidos = generosEscolhidos;
	}

	public TipoGenero[] getTodosOsGeneros() {
		return todosOsGeneros;
	}
	
	public void escolherTodosOsGeneros() {
		if (allGeneros == true) {
			generosEscolhidos = todosOsGeneros ;
		}
	}
	
	public void changeEscolherTodosOsGeneros() {
		allGeneros = false ;
	}

	public boolean isAllGeneros() {
		return allGeneros;
	}

	public void setAllGeneros(boolean allGeneros) {
		this.allGeneros = allGeneros;
	}
	
	public void escolherTodosOsPaises() {
		if (allPaises == true) {
			paisesEscolhidos = todosOsPaises ;
		}
	}
	
	public void changeEscolherTodosOsPaises() {
		allPaises = false ;
	}

	public boolean isAllPaises() {
		return allPaises;
	}

	public void setAllPaises(boolean allPaises) {
		this.allPaises = allPaises;
	}

}