package br.ufes.informatica.musicplus.core.application;

import java.io.Serializable;
import java.util.List;

import javax.ejb.Local;

import br.ufes.informatica.musicplus.core.domain.Artista;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface ArtistaService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public void save(Artista artista) ;

	public List<Artista> buscarPorNome(String nome) ;
}