package br.ufes.informatica.musicplus.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.musicplus.core.persistence.MusicaDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class MusicaServiceBean implements MusicaService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private MusicaDAO musicaDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List buscarMusica(String NomeDaMusica, String NomeDoArtista) {
		// FIXME: auto-generated method stub
		return null;
	}

}