package br.ufes.informatica.musicplus.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.musicplus.core.domain.Musica;
import br.ufes.informatica.musicplus.core.domain.Usuario;
import br.ufes.informatica.musicplus.core.persistence.PlaylistDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class PlaylistServiceBean implements PlaylistService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private PlaylistDAO playlistDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void criarPlaylist(String nomePlaylist) {
		// FIXME: auto-generated method stub
		return;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void adicionarMusicaNaPlaylist(Usuario usuarioLogado, Musica musicaAtual, String nomePlaylist) {
		// FIXME: auto-generated method stub
		return;
	}

}