package br.ufes.informatica.musicplus.core.application;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.informatica.musicplus.core.domain.Musica;
import br.ufes.informatica.musicplus.core.domain.Usuario;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface PlaylistService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public void criarPlaylist(String nomePlaylist);

	/** TODO: generated by FrameWeb. Should be documented. */
	public void adicionarMusicaNaPlaylist(Usuario usuarioLogado, Musica musicaAtual, String nomePlaylist);

	/** TODO: generated by FrameWeb. Should be documented. */
	public void removerMusicaDaPlaylist(Usuario usuarioLogado, Musica musicaAtual, String nomePlaylist);

	/** TODO: generated by FrameWeb. Should be documented. */
	public void listarMusicasDaPlaylist(Usuario usuarioLogado, String nomePlaylist);

}