package br.ufes.informatica.musicplus.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class PlaylistServiceBean implements PlaylistService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private PlaylistDAO playlistDAO;
	
	
	

	
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void criarPlaylist(String nomePlaylist) {
		// FIXME: auto-generated method stub
		return;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void adicionarMusicaNaPlaylist(Usuario usuarioLogado, Musica musicaAtual, String nomePlaylist) {
		// FIXME: auto-generated method stub
		return;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void removerMusicaDaPlaylist(Usuario usuarioLogado, Musica musicaAtual, String nomePlaylist) {
		// FIXME: auto-generated method stub
		return;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void listarMusicasDaPlaylist(Usuario usuarioLogado, String nomePlaylist) {
		// FIXME: auto-generated method stub
		return;
	}
	
}