package br.ufes.informatica.musicplus.core.application;

import java.util.List;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.musicplus.core.domain.Musica;
import br.ufes.informatica.musicplus.core.domain.Playlist;
import br.ufes.informatica.musicplus.core.domain.Usuario;
import br.ufes.informatica.musicplus.core.persistence.PlaylistDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class PlaylistServiceBean implements PlaylistService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private PlaylistDAO playlistDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void criarPlaylist(Usuario UsuarioLogado, String nomePlaylist) {
		Playlist p = new Playlist();
		p.setNome(nomePlaylist);
		p.setUsuario(UsuarioLogado);
		playlistDAO.save(p);
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void adicionarMusicaNaPlaylist(Usuario usuarioLogado, Musica musicaAtual, String nomePlaylist) {
		// FIXME: auto-generated method stub
		return;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void removerMusicaDaPlaylist(Usuario usuarioLogado, Musica musicaAtual, String nomePlaylist) {
		// FIXME: auto-generated method stub
		return;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void listarMusicasDaPlaylist(Usuario usuarioLogado, String nomePlaylist) {
		// FIXME: auto-generated method stub
		return;
	}

	@Override
	public void deletarPlaylist(Playlist playlist) {
		playlistDAO.delete(playlist);
	}

	@Override
	public Playlist buscarPorNome(Usuario usuarioLogado, String nomePlaylist) {
		// TODO Auto-generated method stub
		List<Playlist> playlists = playlistDAO.buscarPorUsuario(usuarioLogado);
		if (playlists == null) {
			return null ;
		}
		for (Playlist p : playlists) {
			if (p.getNome().equals(nomePlaylist)){
				return p ;
			}
		}
		return null ;
	}

}