package br.ufes.informatica.musicplus.core.application;

import java.io.Serializable;
import java.util.List;

import javax.ejb.Local;

import br.ufes.informatica.musicplus.core.domain.TipoGenero;
import br.ufes.informatica.musicplus.core.domain.TipoIdioma;
import br.ufes.informatica.musicplus.core.domain.TipoPais;
import br.ufes.informatica.musicplus.core.domain.Artista;
import br.ufes.informatica.musicplus.core.domain.Musica;


/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface SugestaoService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Artista> pedirSugestaoArtista(String rankingOuAleatorio, List<TipoPais> pais, Integer numero, List<TipoGenero> genero);

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Musica> pedirSugestaoMusica(String RankingOuAleatorio, List<TipoIdioma> idioma, Integer numero, List<TipoGenero> genero);

}