package br.ufes.informatica.musicplus.core.application;

import java.util.List;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.musicplus.core.domain.Usuario;
import br.ufes.informatica.musicplus.core.persistence.UsuarioDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class UsuarioServiceBean implements UsuarioService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	@EJB
	private UsuarioDAO usuarioDAO;

	public void save(Usuario usuario) {
		usuarioDAO.save(usuario);
	}


}