package br.ufes.informatica.musicplus.core.application;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.informatica.musicplus.core.domain.Usuario;


/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface UsuarioService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public void save(Usuario usuario);

}