package br.ufes.informatica.musicplus.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class PlaylistController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private PlaylistService playlistService;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Musica musicaAtual;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Playlist playlist;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Usuario usuarioLogado;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String adicionarMusicaNaPlaylist() {
		// FIXME: auto-generated method stub
		return null;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public String criarPlaylist() {
		// FIXME: auto-generated method stub
		return null;
	}
	
	
	
	/** Getter for musicaAtual. */
	public Musica getMusicaAtual() {
		return musicaAtual;
	}

	/** Setter for musicaAtual. */
	public void setMusicaAtual(Musica musicaAtual) {
		this.musicaAtual = musicaAtual;
	}
	
	/** Getter for playlist. */
	public Playlist getPlaylist() {
		return playlist;
	}

	/** Setter for playlist. */
	public void setPlaylist(Playlist playlist) {
		this.playlist = playlist;
	}
	
	/** Getter for usuarioLogado. */
	public Usuario getUsuarioLogado() {
		return usuarioLogado;
	}

	/** Setter for usuarioLogado. */
	public void setUsuarioLogado(Usuario usuarioLogado) {
		this.usuarioLogado = usuarioLogado;
	}
	
}