package br.ufes.informatica.musicplus.core.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.ManyToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Musica extends PersistentObjectSupport implements Comparable<Musica> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String duracao;

	@ManyToMany(mappedBy = "musicasFavoritadas")
	private Set<Usuario> usuariosQueFavoritaram;
	
	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
    @Enumerated(EnumType.STRING)
	private TipoIdioma idioma;

	/** TODO: generated by FrameWeb. Should be documented. false */
    @ElementCollection(fetch = FetchType.EAGER)
	private List<TipoGenero> generos;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private int numVezesFavoritado;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@Temporal(TemporalType.DATE)
	private Date dataLancamento;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany(mappedBy = "musicas")
	private Set<Album> colecoes;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany(fetch = FetchType.EAGER)
	private Set<Artista> artistas;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany(mappedBy = "musicas")
	private Set<Playlist> playlists;

	/** Getter for nome. */
	public String getNome() {
		return nome;
	}

	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for duracao. */
	public String getDuracao() {
		return duracao;
	}

	/** Setter for duracao. */
	public void setDuracao(String duracao) {
		this.duracao = duracao;
	}

	/** Getter for idioma. */
	public TipoIdioma getIdioma() {
		return idioma;
	}
	
	public void setIdioma(TipoIdioma idioma) {
		this.idioma = idioma;
	}

	/** Getter for genero. */
	public List<TipoGenero> getGenero() {
		return generos;
	}

	/** Getter for numVezesFavoritado. */
	public int getNumVezesFavoritado() {
		return numVezesFavoritado;
	}

	/** Setter for numVezesFavoritado. */
	public void setNumVezesFavoritado(int numVezesFavoritado) {
		this.numVezesFavoritado = numVezesFavoritado;
	}

	/** Getter for dataLancamento. */
	public Date getDataLancamento() {
		return dataLancamento;
	}

	/** Setter for dataLancamento. */
	public void setDataLancamento(Date dataLancamento) {
		this.dataLancamento = dataLancamento;
	}

	/** Getter for Target. */
	public Set<Album> getColecoes() {
		return colecoes;
	}

	/** Getter for Source. */
	public Set<Artista> getArtistas() {
		return artistas;
	}

	/** Getter for Source. */
	public Set<Playlist> getPlaylists() {
		return playlists;
	}
	
	public String imprimirGeneros() {
		String gens = "";
		for (TipoGenero g : this.generos) {
			gens = gens + "; " + g ;
		}
		gens = gens.replaceFirst("; ","");
		return gens ;
	}
	
	public String imprimirArtistas() {
		String musicos = "";
		for (Artista m : this.artistas) {
			musicos = musicos + "; " + m.getNome() ;
		}
		musicos = musicos.replaceFirst("; ","");
		return musicos ;
	}
	
	public void addGenero(TipoGenero genero) {
		this.generos.add(genero) ;
	}
	
	public void addArtista(Artista artista) {
		this.artistas.add(artista) ;
	}
	
	public void removerArtista(Artista artista) {
		this.artistas.remove(artista) ;
	}
	
	public Musica() {
		super();
		this.generos = new ArrayList<TipoGenero>();
		this.artistas = new HashSet<Artista>();
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Musica o) {
		if (this.getId() == o.getId())
			return 0 ;
		else {
			if (this.numVezesFavoritado == o.numVezesFavoritado) {
				return this.nome.compareTo(o.nome); 
			}else {
				Integer thisNumVezesFavoritado = this.numVezesFavoritado;
				Integer oNumVezesFavoritado = o.numVezesFavoritado;
				return oNumVezesFavoritado.compareTo(thisNumVezesFavoritado); 
			}
		}
	}

	public void incrementaNumVezesFavoritado() {
		this.numVezesFavoritado = this.numVezesFavoritado + 1 ;
	}

	public void decrementaNumVezesFavorito() {
		this.numVezesFavoritado = this.numVezesFavoritado - 1 ;
		
	}
}