package br.ufes.informatica.musicplus.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Pessoa extends PersistentObjectSupport implements Comparable<Pessoa> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	  
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String username;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String email;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String senha;







	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for username. */
	public String getUsername() {
		return username;
	}
	
	/** Setter for username. */
	public void setUsername(String username) {
		this.username = username;
	}

	/** Getter for email. */
	public String getEmail() {
		return email;
	}
	
	/** Setter for email. */
	public void setEmail(String email) {
		this.email = email;
	}

	/** Getter for senha. */
	public String getSenha() {
		return senha;
	}
	
	/** Setter for senha. */
	public void setSenha(String senha) {
		this.senha = senha;
	}








	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Pessoa o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}