package br.ufes.informatica.musicplus.core.domain;

/** TODO: generated by FrameWeb. Should be documented. */
public enum TipoPais {
	Brasil, EUA, Mexico ;
	
	public static TipoPais[] todos() {
		return (new TipoPais[] { 
				TipoPais.Brasil, 
				TipoPais.EUA, 
				TipoPais.Mexico
				});
	}
}