package br.ufes.informatica.musicplus.core.domain;

/** TODO: generated by FrameWeb. Should be documented. */
public enum TipoGenero {
	Pop, Samba, Indie, Eletronica, Rock, Jazz, Country, Gospel, Qualquer_Genero;
	
	public static TipoGenero[] todosMenosQualquerUm() {
		return (new TipoGenero[] { 
				TipoGenero.Pop, 
				TipoGenero.Samba, 
				TipoGenero.Indie,
				TipoGenero.Eletronica,
				TipoGenero.Rock,
				TipoGenero.Jazz,
				TipoGenero.Country,
				TipoGenero.Gospel
				});
	}
}