package br.ufes.informatica.musicplus.core.domain;

/** TODO: generated by FrameWeb. Should be documented. */
public enum TipoIdioma {
	Ingles, Portugues, Espanhol, Nenhum;
	
	public static TipoIdioma[] todos() {
		return (new TipoIdioma[] { 
				TipoIdioma.Ingles, 
				TipoIdioma.Portugues, 
				TipoIdioma.Espanhol,
				TipoIdioma.Nenhum
				});
	}
}