package br.ufes.informatica.musicplus.core.domain;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Usuario extends PersistentObjectSupport implements Comparable<Usuario> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */

	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */
	
	@NotNull
	@Enumerated(EnumType.STRING)
	private TipoUsuario admin ;

	@NotNull
	private String username;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String email;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String senha;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany
	private Set<Artista> artistasFavoritados;
	
	/** TODO: generated by FrameWeb. Should be documented. false */
    @ElementCollection
	private List<TipoGenero> generoFavoritados;
    
	/** Getter for generoFavoritados. */
	public List<TipoGenero> getGeneroFavoritados() {
		return generoFavoritados;
	}

	/** Setter for generoFavoritados. */
	public void setGeneroFavoritados(List<TipoGenero> generoFavoritados) {
		this.generoFavoritados = generoFavoritados;
	}
	
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Set<Artista> getArtistasFavoritados() {
		return artistasFavoritados;
	}

	public Set<Musica> getMusicasFavoritadas() {
		return musicasFavoritadas;
	}

	@ManyToMany
	private Set<Musica> musicasFavoritadas;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToMany(
			cascade = CascadeType.ALL,
			mappedBy = "usuario")
	private Set<Playlist> playlists;

	/** Getter for Target. */
	public Set<Playlist> getPlaylists() {
		return playlists;
	}
	
	/** Getter for nome. */
	public String getNome() {
		return nome;
	}

	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for username. */
	public String getUsername() {
		return username;
	}

	/** Setter for username. */
	public void setUsername(String username) {
		this.username = username;
	}

	/** Getter for email. */
	public String getEmail() {
		return email;
	}

	/** Setter for email. */
	public void setEmail(String email) {
		this.email = email;
	}

	/** Getter for senha. */
	public String getSenha() {
		return senha;
	}

	/** Setter for senha. */
	public void setSenha(String senha) {
		this.senha = senha;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Usuario o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
	
	

	public TipoUsuario getAdmin() {
		return admin;
	}

	public void setAdmin(TipoUsuario admin) {
		this.admin = admin;
	}

	public void addGenero(TipoGenero g) {
		// TODO Auto-generated method stub
		this.generoFavoritados.add(g);
	}
	
	public Usuario() {
		super();
		this.generoFavoritados = new ArrayList<TipoGenero>(); 
	}

}