package br.ufes.informatica.musicplus.core.domain;

import java.util.List;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Usuario extends PersistentObjectSupport implements Comparable<Usuario> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private List<TipoGenero> generoFavoritados;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToMany(mappedBy = "Source")
	private Set<Playlist> Playlists;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany
	private Set<Artista> ArtistasFavoritados;

	/** Getter for generoFavoritados. */
	public List getGeneroFavoritados() {
		return generoFavoritados;
	}

	/** Setter for generoFavoritados. */
	public void setGeneroFavoritados(List generoFavoritados) {
		this.generoFavoritados = generoFavoritados;
	}

	/** Getter for Target. */
	public Set<Playlist> getPlaylists() {
		return Playlists;
	}

	/** Setter for Target. */
	public void setPlaylists(Set<Playlist> Playlists) {
		this.Playlists = Playlists;
	}

	/** Getter for Target. */
	public Set<Artista> getArtistasFavoritados() {
		return ArtistasFavoritados;
	}

	/** Setter for Target. */
	public void setArtistasFavoritados(Set<Artista> ArtistasFavoritados) {
		this.ArtistasFavoritados = ArtistasFavoritados;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Usuario o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}